version: '3.4'

services:
  website:
    image: frontend-website
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: website
    ports:
      - "3000:3000"
      - "3001:3001"
    networks:
      - api

networks:    
  api:
    driver: bridge